[package]
name = "divide_et_impera_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "divide_et_impera_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
